-- ═══════════════════════════════════════════════════════════════════════
-- MIGRATION PRODUCTION — Supabase / PostgreSQL
-- Fonctionnalités : inscription publique des hôpitaux + abonnements + paiements
-- À COLLER dans : Supabase Dashboard → SQL Editor → New query → Run
-- Idempotent : réexécutable sans risque (IF NOT EXISTS / ON CONFLICT).
-- ═══════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- 1) TABLE hospitals : colonnes d'inscription + d'abonnement
-- ─────────────────────────────────────────────────────────────
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS registration_status         VARCHAR(20);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS requested_admin_first_name  VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS requested_admin_last_name   VARCHAR(255);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS requested_admin_phone       VARCHAR(50);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS rejection_reason            TEXT;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS subscription_status         VARCHAR(20);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS subscription_type           VARCHAR(20);
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS subscription_start          DATE;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS subscription_end            DATE;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS last_subscription_alert     VARCHAR(20);

-- Les hôpitaux existants sont considérés déjà approuvés (NULL = APPROVED dans le code,
-- on fixe la valeur explicitement pour la cohérence).
UPDATE hospitals SET registration_status = 'APPROVED' WHERE registration_status IS NULL;
ALTER TABLE hospitals ALTER COLUMN registration_status SET DEFAULT 'APPROVED';

-- ─────────────────────────────────────────────────────────────
-- 2) TABLE subscription_settings : configuration globale (ligne unique id=1)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscription_settings (
    id                       BIGINT PRIMARY KEY,
    currency                 VARCHAR(10),
    standard_monthly_price   NUMERIC(12,2),
    premium_monthly_price    NUMERIC(12,2),
    enterprise_monthly_price NUMERIC(12,2),
    annual_discount_percent  NUMERIC(5,2),
    trial_days               INTEGER,
    grace_days               INTEGER,
    alert_days_before        INTEGER,
    auto_approve             BOOLEAN,
    updated_at               TIMESTAMP
);
-- Au cas où la table existait déjà sans cette colonne
ALTER TABLE subscription_settings ADD COLUMN IF NOT EXISTS auto_approve BOOLEAN;

-- Réglages par défaut (l'application les crée aussi au 1er accès, mais on les sème ici)
INSERT INTO subscription_settings
    (id, currency, standard_monthly_price, premium_monthly_price, enterprise_monthly_price,
     annual_discount_percent, trial_days, grace_days, alert_days_before, auto_approve, updated_at)
VALUES (1, 'USD', 50, 100, 200, 15, 14, 3, 5, TRUE, NOW())
ON CONFLICT (id) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 3) TABLE subscription_payments : historique des paiements
--    id : identité (GENERATED BY DEFAULT AS IDENTITY) pour coller à Hibernate.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscription_payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id      BIGINT NOT NULL REFERENCES hospitals(id),
    plan             VARCHAR(30),
    period           VARCHAR(20),
    amount           NUMERIC(12,2),
    currency         VARCHAR(10),
    method           VARCHAR(30),
    status           VARCHAR(20),
    reference        VARCHAR(60) UNIQUE,
    payer_name       VARCHAR(255),
    payer_detail     VARCHAR(255),
    period_start     DATE,
    period_end       DATE,
    confirmed_by     VARCHAR(255),
    confirmed_at     TIMESTAMP,
    rejection_reason TEXT,
    created_at       TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subpay_hospital ON subscription_payments(hospital_id);
CREATE INDEX IF NOT EXISTS idx_subpay_status   ON subscription_payments(status);

-- ─────────────────────────────────────────────────────────────
-- 4) VÉRIFICATION rapide
-- ─────────────────────────────────────────────────────────────
SELECT 'hospitals (registration_status non nul)' AS objet, count(*)::text AS valeur
  FROM hospitals WHERE registration_status IS NOT NULL
UNION ALL SELECT 'subscription_settings (lignes)', count(*)::text FROM subscription_settings
UNION ALL SELECT 'subscription_payments (lignes)', count(*)::text FROM subscription_payments;
