-- ★ MIGRATION: Création de la table exchange_rates
-- Permet de stocker les taux de conversion entre devises
-- L'admin peut configurer dynamiquement le taux USD/FC

CREATE TABLE IF NOT EXISTS exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_from VARCHAR(3) NOT NULL,
    currency_to VARCHAR(3) NOT NULL,
    rate NUMERIC(19, 6) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT true,
    updated_by BIGINT,
    updated_by_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index pour optimiser les recherches
CREATE INDEX IF NOT EXISTS idx_exchange_rates_pair 
    ON exchange_rates (currency_from, currency_to, is_active);

CREATE INDEX IF NOT EXISTS idx_exchange_rates_active 
    ON exchange_rates (is_active);

-- Insertion du taux par défaut USD/FC (2800)
-- Ce taux sera utilisé pour les conversions dans le catalogue des services
INSERT INTO exchange_rates (currency_from, currency_to, rate, description, is_active, updated_by_name)
SELECT 'USD', 'FC', 2800.000000, 'Taux par défaut USD vers Francs Congolais', true, 'System'
WHERE NOT EXISTS (
    SELECT 1 FROM exchange_rates 
    WHERE currency_from = 'USD' AND currency_to = 'FC' AND is_active = true
);

-- Commentaire sur la table
COMMENT ON TABLE exchange_rates IS 'Stocke les taux de change entre devises. Géré par l''admin dans Configuration > Finance.';
COMMENT ON COLUMN exchange_rates.rate IS 'Taux de conversion (ex: 2800 pour 1 USD = 2800 FC)';
COMMENT ON COLUMN exchange_rates.is_active IS 'Indique si ce taux est actuellement utilisé';
