# ===============================
# CONFIGURATION DE L'APPLICATION
# ===============================
spring.application.name=hospital-backend
server.port=8080
server.error.include-message=always

# ===============================
# BASE DE DONNEES (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=INUA

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SÉCURITÉ JWT
# ===============================
jwt.secret=MaCleSecreteInuaAfiaTresLonguePourLaSecuriteDuCliniqueUCBC2025
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# GESTION DES FICHIERS (IMAGES)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/profiles

# ===============================
# CONFIGURATION SERVEUR (TOMCAT)
# ===============================
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.address=0.0.0.0

# ============================================================
# CONFIGURATION JSON (JACKSON) - RÉPARATION AFFICHAGE REACT
# ============================================================
# 1. Transforme les dates [2026, 3, 4] en format texte "2026-03-04"
# Sans cela, React ne peut pas lire la date de naissance.
spring.jackson.serialization.write-dates-as-timestamps=false

# 2. Force la conversion automatique du snake_case vers camelCase
# Exemple: La colonne SQL 'health_area' deviendra 'healthArea' dans le JSON.
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE

# 3. Inclut les champs même s'ils sont vides pour éviter les "undefined" dans React
spring.jackson.default-property-inclusion=always
