# ===============================
# CONFIGURATION DE L'APPLICATION
# ===============================
spring.application.name=hospital-backend
server.port=8080
server.error.include-message=always

# ===============================
# BASE DE DONNEES (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=INUA
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SÉCURITÉ JWT
# ===============================
jwt.secret=MaCleSecreteInuaAfiaTresLonguePourLaSecuriteDuCliniqueUCBC2025
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# GESTION DES FICHIERS (IMAGES)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/profiles

# ===============================
# CONFIGURATION SERVEUR (TOMCAT)
# ===============================
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.address=0.0.0.0

# ===============================
# EMAIL (dummy pour local)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@example.com
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.email.from=dummy@example.com

# ============================================================
# CONFIGURATION JSON (JACKSON)
# ====================================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jackson.default-property-inclusion=always